### ISSUE TITLE
Using Servo and Scratch

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2-pi#2]
Hi, first of all congratulation for this development.
I am a big fan of your work.
Do you know if is possible to add a servo control (to use scratch blocks controlling a servo) in s2-pi as it's available in s2aio?

Thanks in advance

**Comment by MrYsLab** [comment]
I will look into doing this, but I can not give you a time frame when it might be done. In the meantime, you can take a look at this article on [controlling a servo with PWM](https://rpi.science.uoit.ca/lab/servo/). If you try it out, please let me know if you were successful and it if meets your needs.

**Comment by sobreira** [comment]
Thanks I will check it

**Comment by sobreira** [comment]
Hi Alan, 
I found a reference using [pigpio,](https://www.raspberrypi.org/forums/viewtopic.php?t=115513) as you wrote your code using this.
Maybe you can have a look in an appropriate time and highlight some mistakes.
Changes are made in 2 files: s2_pi.js and s2_pi.py
I have placed a comment started as HackEduca in the place I have changed

Thanks a lot.
[s2-pi.zip](https://github.com/MrYsLab/s2-pi/files/2532269/s2-pi.zip)

Edson Sobreira
HackEduca

**Comment by MrYsLab** [comment]
That looks great. I was able to install and bring up Scratch with your blocks but, I have not had a chance to hook up a servo to my RPi. Have you tested and does it work?
I am really glad that you were able to create your own blocks and to modify the server.

**Comment by sobreira** [comment]
You have made the code well structured - it makes easier to understand -
even for me who lacks knowledge in Python language.
I have hooked up and worked fine - at least the version I shared with you.

I have asked for a collegue test it in their school. Let's see if he catch
any error.

Em qua, 31 de out de 2018 às 10:11, Alan Yorinks <notifications@github.com>
escreveu:

**Comment by MrYsLab** [comment]
Great Work!!! If you are familiar with submitting a pull request for Github, please feel free to do so. By submitting the pull request your name will be added to the list of contributors for s2-pi. If you are unfamiliar with pull requests, no problem. I can add your code to the distribution and give you full credit.

Please let me know what you would like to do when you get your test results back.

Also, thank you for the great feedback. I developed s2-pi with the hope that users could create their own Scratch extensions for the Raspberry Pi to meet their own needs.
You did just that and it made me very happy :-)

**Comment by sobreira** [comment]
Thanks!
My colleague just tested a lot without any issues.
I have made a pull request - hope it works

**Comment by MrYsLab** [comment]
Hi. I don't see the pull request. Github is not the easiest of tools to understand. If you like, I can update the files and give you credit for your work. If you want to go ahead with the pull request, here is a [tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github), but as you will see it is complicated.

Please let me know if you want me to incorporate your code or if you want to go ahead with the pull request.

Thanks.

**Comment by sobreira** [comment]
Got it, actually I have created a pull request against my forked project.
Please to check it again, if not worked go ahed with your suggestion. Fine for me.
Also, feel free to change/remove the comment.

**Comment by MrYsLab** [comment]
I see the pull request. I will merge after I update the User's Guide with your changes. I should be able to get it done in a day or so.

**Comment by MrYsLab** [comment]
@sobreira I accepted the pull request, but made a few minor changes:
1. Removed the reference to Rpi.GPIO.
2. Change the case sensitivity of your variable names - for example, DegreeMin  -> degree_min.
3. Added space after the # marks in your comment.
4. Moved your comment from above 
elif client_cmd == 'servo': to below that line.

I have committed these changes but just wanted to make sure they are ok with you.

If not, please feel free to do another pull request.

Also, I will be updating the User Guide to include your new block and I also added you as a contributor.

**Comment by sobreira** [comment]
Thanks!!


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui, 1 de nov de 2018 às 20:51, Alan Yorinks <notifications@github.com>
escreveu:

**Comment by MrYsLab** [comment]
Implemented in release 1.21. Thanks for all your work!
