### ISSUE TITLE
Clarification for Scratch setup (Using The s2-pi Blocks section?) 

### ISSUE THREAD

**Issue by RocketPop** [MrYsLab/s2-pi#6]
Hi -thanks for this plugin! I just wanted to point out something that was a bit confusing to me. If you place the `connect to s2_pi server` block under ANYTHING that is executed more than once (like the green flag), you will get confusing behavior - specifically for inputs. You will get multiple connections to the daemon and each connection will trigger the input callback (you can see this from the terminal `s2pi` output). Then if you restart the sketch again (like with the "green flag") you will reconnect another time - leading to 3x the callbacks and so on... So it might be nice to update the setup section to mention that the `connect to s2_pi server` and any `set BCM PIN as an Input` commands need to be placed on the sketch and must be triggered ONCE by the user manually when they open the sketch. Any other placement or usage of these setup blocks will lead to multiple callbacks for the input changes - which (depending on your sketch) can do unexpected things :)

**Comment by MrYsLab** [comment]
Thanks for the comment. I updated the connection section with a special note.
